# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock, etc.)
# This is a key optimization. These files are copied first, and `npm install` is run.
# Docker will cache this layer. As long as these files don't change, Docker
# won't re-run `npm install` on subsequent builds, speeding up the process.
COPY package.json ./
COPY package-lock.json ./

# Install any needed packages
RUN npm install

# Copy the rest of the application's source code
COPY . .

# Make port 5173 available to the world outside this container
# This is the port Vite runs on by default
EXPOSE 5173

# Run the app when the container launches
# `npm run dev` is defined in `package.json` as `vite --host`
CMD ["npm", "run", "dev"]
